<?php

/**
 * An Inputfield for handling XHTML "text" form inputs
 *
 */
class InputfieldForm extends InputfieldWrapper {

	public static function getModuleInfo() {
		return array(
			'title' => 'Form',
			'version' => 100,
			'summary' => 'Contains one or more fields in a form',
			'permanent' => true, 
			);
	}

	public function __construct() {
		parent::__construct();
		$this->setAttribute('method', 'post'); 
		$this->setAttribute('action', './'); 
	}

	public function ___render() {

		$attrs = $this->getAttributes();
		unset($attrs['value']); 

		$description = $this->getSetting('description'); 
		if($description) $description = "\n<h2>" . htmlspecialchars($description) . "</h2>"; 

		$out = 	"\n<form " . $this->getAttributesString($attrs) . ">" . 
			$description . 
			parent::___render() . 	
			"\n</form>";

		return $out; 
	}
	
}

