<?php

/**
 * ProcessWire Entities Textformatter
 *
 * Formats text with PHP's htmlspecialchars() function.
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2010 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class TextformatterEntities extends Textformatter {

	public static function getModuleInfo() {
		return array(
			'title' => 'HTML Entity Encoder (htmlspecialchars)', 
			'version' => 100, 
			'summary' => "Entity encode ampersands, quotes (single and double) and greater-than/less-than signs using htmlspecialchars(str, ENT_QUOTES).", 
		); 
	}

	public function format(&$str) {
		$str = htmlspecialchars($str, ENT_QUOTES); 
	}
}
